'use client';

import Link from 'next/link';
import { useSurveys } from '../../../lib/survey/useSurveys';

export default function SurveysPage() {
  const { surveys, deleteSurvey: removeSurvey, duplicateSurvey: cloneSurvey } = useSurveys();

  return <main className="min-h-svh bg-background px-5 py-8 text-foreground"><div className="mx-auto max-w-5xl"><header className="mb-8 flex flex-wrap items-end justify-between gap-4 border-b border-border pb-6"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-brand">Workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Surveys</h1><p className="mt-2 text-sm text-muted-foreground">Saved survey definitions ready to run or review.</p></div><Link href="/survey-builder" className="rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90">Create survey</Link></header>{surveys.length === 0 ? <div className="rounded-xl border border-dashed border-border bg-card px-6 py-12 text-center"><p className="text-sm text-muted-foreground">No saved surveys yet.</p><Link href="/survey-builder" className="mt-4 inline-block text-sm font-medium text-brand hover:underline">Open the builder</Link></div> : <div className="grid gap-3">{surveys.map((survey) => <article key={survey.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-border bg-card p-5"><div><h2 className="font-medium text-foreground">{survey.name}</h2><p className="mt-1 text-xs text-muted-foreground">{survey.schema.title} · Created {new Date(survey.createdAt).toLocaleString()}</p></div><div className="flex items-center gap-2"><Link href={`/survey-builder?surveyId=${survey.id}`} className="rounded-md border border-border px-3 py-2 text-xs font-medium text-foreground hover:bg-muted">Edit</Link><Link href={`/survey/${survey.id}`} className="rounded-md border border-border px-3 py-2 text-xs font-medium text-foreground hover:bg-muted">Run survey</Link><Link href={`/report/${survey.id}`} className="rounded-md border border-border px-3 py-2 text-xs font-medium text-foreground hover:bg-muted">View report</Link><button type="button" onClick={() => cloneSurvey(survey.id)} className="rounded-md border border-border px-3 py-2 text-xs font-medium text-foreground hover:bg-muted">Duplicate</button><button type="button" onClick={() => removeSurvey(survey.id)} className="rounded-md px-3 py-2 text-xs font-medium text-muted-foreground hover:bg-destructive/10 hover:text-destructive">Delete</button></div></article>)}</div>}</div></main>;
}
